<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>OpenForge.Cli.Framework</AssemblyName>
    <RootNamespace>OpenForge.Cli.Core</RootNamespace>
    <IsAotCompatible>true</IsAotCompatible>
    <IsTrimmable>true</IsTrimmable>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
    <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" />
    <PackageReference Include="YamlDotNet" />
    <PackageReference Include="Vecc.YamlDotNet.Analyzers.StaticGenerator" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="../../../open-forge/**/*"
                      LogicalName="OpenForge.Framework.Payload/%(RecursiveDir)%(Filename)%(Extension)"
                      WithCulture="false" />
    <EmbeddedResource Include="../../../extensions/**/*"
                      Exclude="../../../extensions/README.md"
                      LogicalName="OpenForge.Extensions.Payload/%(RecursiveDir)%(Filename)%(Extension)"
                      WithCulture="false" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>OpenForge.Cli.Shell</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>OpenForge.Cli.Operations</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>OpenForge.Cli</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>OpenForge.Cli.Core.UnitTests</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>OpenForge.Cli.IntegrationTests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
