<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>OpenForge.Cli.TestSupport</AssemblyName>
    <RootNamespace>OpenForge.Cli.TestSupport</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="../../../../extensions/**/extension.json"
                      LogicalName="OpenForge.Tests.ExtensionManifests/%(RecursiveDir)%(Filename)%(Extension)"
                      WithCulture="false" />
  </ItemGroup>
</Project>
