using System.Text.Json;
using OpenForge.Cli.EndToEndTests.Shared.PublishedProcess;
using OpenForge.Cli.TestSupport;

namespace OpenForge.Cli.EndToEndTests;

public sealed class PublishedDoctorGeneratedNavigationProcessTests
{
    private const string PlanningCataloguePath = ".agents/skills/use-workflow/references/planning/_planning.md";
    private const string DetachedPlanningCataloguePath = ".agents/skills/use-workflow/references/detached/planning/_planning.md";
    private const string DetachedBetaProbePath = ".agents/skills/use-workflow/references/detached/planning/beta-probe.md";
    private const string DefaultIndexProbePath = ".agents/skills/use-workflow/references/planning/default-index-probe.md";
    private const string WorkflowSkillPath = ".agents/skills/use-workflow/SKILL.md";

    [Theory(DisplayName = "Doctor accepts current navigation generated by Extension installation"),
        InlineData("development", "doctor"), InlineData("development-toolkit", "doctor"),
        InlineData("development", "status"), InlineData("development-toolkit", "status"),
        Trait("Feature", "doctor-generated-navigation"), Trait("Evidence", "EndToEnd")]
    public async Task FreshExtensionNavigationIsNotFrameworkDrift(string id, string command)
    {
        var target = PublishedExecutableTarget.Discover();
        using var workspace = PublishedExtensionInstallWorkspace.Create();
        await ApplyAsync(target, workspace, ["install", "--automatic", "--format=json"]);
        await ApplyAsync(target, workspace, ["extension", "install", id, "--automatic", "--format=json"]);

        var run = await DiagnoseAsync(target, workspace, command);

        Assert.True(run.ExitCode == 0, $"Expected exit 0, got {run.ExitCode}. Stdout: {run.StandardOutput} Stderr: {run.StandardError}");
        using var document = JsonDocument.Parse(run.StandardOutput);
        Assert.Equal("completed", document.RootElement.GetProperty("status").GetString());
        if (command == "doctor")
        {
            Assert.Empty(Findings(document, "framework-lifecycle"));
            Assert.Empty(Findings(document, "routes-metadata-overwrites-generated-navigation"));
        }
    }

    [Fact(DisplayName = "Doctor advertises the owning catalogue for a detached planning recipe"),
        Trait("Feature", "doctor-generated-navigation"), Trait("Evidence", "EndToEnd")]
    public async Task DetachedPlanningRecipeUsesOwningCatalogueIndexAction()
    {
        var target = PublishedExecutableTarget.Discover();
        using var workspace = PublishedExtensionInstallWorkspace.Create();
        await ApplyAsync(target, workspace, ["install", "--automatic", "--format=json"]);
        await ApplyAsync(
            target,
            workspace,
            ["extension", "install", "planning", "--automatic", "--format=json"]);

        var workflowSkillPath = Path.Combine(
            workspace.WorkspacePath,
            WorkflowSkillPath.Replace('/', Path.DirectorySeparatorChar));
        Assert.True(File.Exists(workflowSkillPath));
        var workflowSkillBytes = File.ReadAllBytes(workflowSkillPath);

        var recipePath = Path.Combine(
            workspace.WorkspacePath,
            DetachedBetaProbePath.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(recipePath)
            ?? throw new InvalidOperationException("The detached planning recipe requires a parent directory."));
        await File.WriteAllTextAsync(
            recipePath,
            OpenForgeDocumentSeed.Metadata(
                description: "A beta probe recipe",
                tags: ["Extension", "Workflow", "Planning"],
                body: """
                    # Beta Probe

                    ## Goal

                    Exercise catalogue-specific generated navigation repair.

                    ## Steps

                    1. Run the advertised catalogue-specific Index action.

                    ## Completion

                    The recipe appears in the planning catalogue with its authored bytes preserved.
                    """),
            TestContext.Current.CancellationToken);
        var recipeBytes = File.ReadAllBytes(recipePath);
        var cataloguePath = Path.Combine(
            workspace.WorkspacePath,
            DetachedPlanningCataloguePath.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(cataloguePath)
            ?? throw new InvalidOperationException("The detached planning catalogue requires a parent directory."));
        await File.WriteAllTextAsync(
            cataloguePath,
            OpenForgeDocumentSeed.Metadata(
                description: "Detached planning recipes",
                tags: ["Extension", "Workflow", "Planning"],
                body: OpenForgeDocumentSeed.GeneratedEntries(new GeneratedEntriesSeed
                {
                    Entries = "- stale",
                    Prefix = "# Detached planning recipes",
                })),
            TestContext.Current.CancellationToken);

        var defaultIndex = await ApplyAsync(target, workspace, ["index"]);
        Assert.NotEmpty(defaultIndex.StandardOutput);
        Assert.DoesNotContain(
            "beta-probe.md",
            File.ReadAllText(cataloguePath),
            StringComparison.Ordinal);
        Assert.Contains("- stale", File.ReadAllText(cataloguePath), StringComparison.Ordinal);
        Assert.Equal(workflowSkillBytes, File.ReadAllBytes(workflowSkillPath));
        Assert.Equal(recipeBytes, File.ReadAllBytes(recipePath));

        var diagnosed = await DiagnoseAsync(target, workspace);
        Assert.Equal(2, diagnosed.ExitCode);
        string advertisedTarget;
        using (var document = JsonDocument.Parse(diagnosed.StandardOutput))
        {
            var root = document.RootElement;
            Assert.Equal("completed-with-warnings", root.GetProperty("status").GetString());
            var routeFindings = Findings(document, "routes-metadata-overwrites-generated-navigation");
            Assert.True(
                routeFindings.Length == 1,
                $"Expected one detached-catalogue route finding, got: {string.Join(Environment.NewLine, routeFindings.Select(finding => finding.GetRawText()))}");

            var staleRegion = Assert.Single(
                routeFindings,
                finding => Kind(finding) == "route.generated-region-stale");
            var expectedIndexCommand = $"open-forge index {DetachedPlanningCataloguePath}";

            Assert.Equal("targeted-operation", staleRegion.GetProperty("resolution").GetString());
            Assert.Equal(
                DetachedPlanningCataloguePath,
                staleRegion.GetProperty("subject").GetProperty("path").GetString());
            AssertTargetedIndexAction(staleRegion, expectedIndexCommand);

            var next = root.GetProperty("next");
            Assert.Equal("command", next.GetProperty("kind").GetString());
            var advertisedCommand = next.GetProperty("command").GetString();
            Assert.Equal(expectedIndexCommand, advertisedCommand);
            advertisedTarget = advertisedCommand!["open-forge index ".Length..];
            Assert.Equal(
                "Refresh the generated Entries in this catalogue.",
                next.GetProperty("reason").GetString());
        }

        var targetedIndex = await PublishedProcessTestSupport.RunAsync(
            target,
            workspace.WorkspacePath,
            ["index", advertisedTarget],
            workspace.EnvironmentVariables);
        Assert.Equal(0, targetedIndex.ExitCode);
        Assert.Equal(string.Empty, targetedIndex.StandardError);
        Assert.NotEmpty(targetedIndex.StandardOutput);
        Assert.Contains(
            "beta-probe.md",
            File.ReadAllText(cataloguePath),
            StringComparison.Ordinal);
        Assert.Equal(workflowSkillBytes, File.ReadAllBytes(workflowSkillPath));
        Assert.Equal(recipeBytes, File.ReadAllBytes(recipePath));

        var healed = await DiagnoseAsync(target, workspace);
        Assert.Equal(0, healed.ExitCode);
        using (var document = JsonDocument.Parse(healed.StandardOutput))
        {
            Assert.Equal("completed", document.RootElement.GetProperty("status").GetString());
            Assert.Empty(document.RootElement.GetProperty("findings").EnumerateArray());
        }

        Assert.Contains(
            "beta-probe.md",
            File.ReadAllText(cataloguePath),
            StringComparison.Ordinal);
        Assert.Equal(workflowSkillBytes, File.ReadAllBytes(workflowSkillPath));
        Assert.Equal(recipeBytes, File.ReadAllBytes(recipePath));
    }

    [Fact(DisplayName = "Default Index reaches an installed planning catalogue and is read-only then idempotent")]
    [Trait("Feature", "doctor-generated-navigation"), Trait("Evidence", "EndToEnd")]
    public async Task InstalledPlanningCatalogueUsesDefaultIndexAndDoctorReturnsClean()
    {
        var target = PublishedExecutableTarget.Discover();
        using var workspace = PublishedExtensionInstallWorkspace.Create();
        await ApplyAsync(target, workspace, ["install", "--automatic", "--format=json"]);
        await ApplyAsync(
            target,
            workspace,
            ["extension", "install", "planning", "--automatic", "--format=json"]);

        var workflowSkillPath = Path.Combine(
            workspace.WorkspacePath,
            WorkflowSkillPath.Replace('/', Path.DirectorySeparatorChar));
        var planningCataloguePath = Path.Combine(
            workspace.WorkspacePath,
            PlanningCataloguePath.Replace('/', Path.DirectorySeparatorChar));
        Assert.True(File.Exists(workflowSkillPath));
        Assert.True(File.Exists(planningCataloguePath));
        var workflowSkillBytes = File.ReadAllBytes(workflowSkillPath);

        var recipePath = Path.Combine(
            workspace.WorkspacePath,
            DefaultIndexProbePath.Replace('/', Path.DirectorySeparatorChar));
        await File.WriteAllTextAsync(
            recipePath,
            OpenForgeDocumentSeed.Metadata(
                description: "A default Index probe recipe",
                tags: ["Extension", "Workflow", "Planning"],
                body: "# Default Index probe\n"),
            TestContext.Current.CancellationToken);
        var recipeBytes = File.ReadAllBytes(recipePath);
        var overwritePath = recipePath[..^".md".Length] + ".overwrite.md";
        const string overwriteText = "Authored default Index recipe overwrite.\r\n";
        await File.WriteAllTextAsync(
            overwritePath,
            overwriteText,
            TestContext.Current.CancellationToken);
        var overwriteBytes = File.ReadAllBytes(overwritePath);
        var beforeDryRun = workspace.SnapshotWorkspace();

        var dryRun = await PublishedProcessTestSupport.RunWithoutWritesAsync(
            target,
            workspace.WorkspacePath,
            workspace.SnapshotWorkspace,
            ["index", "--dry-run", "--format=json"],
            workspace.EnvironmentVariables);

        Assert.Equal(0, dryRun.ExitCode);
        Assert.Equal(string.Empty, dryRun.StandardError);
        using (var document = JsonDocument.Parse(dryRun.StandardOutput))
        {
            Assert.Equal("completed", document.RootElement.GetProperty("status").GetString());
        }
        Assert.Equal(beforeDryRun, workspace.SnapshotWorkspace());
        Assert.Equal(workflowSkillBytes, File.ReadAllBytes(workflowSkillPath));
        Assert.Equal(recipeBytes, File.ReadAllBytes(recipePath));
        Assert.Equal(overwriteBytes, File.ReadAllBytes(overwritePath));

        var applied = await PublishedProcessTestSupport.RunAsync(
            target,
            workspace.WorkspacePath,
            ["index", "--format=json"],
            workspace.EnvironmentVariables);

        Assert.Equal(0, applied.ExitCode);
        Assert.Equal(string.Empty, applied.StandardError);
        Assert.Contains("default-index-probe.md", File.ReadAllText(planningCataloguePath), StringComparison.Ordinal);
        Assert.Equal(workflowSkillBytes, File.ReadAllBytes(workflowSkillPath));
        Assert.Equal(recipeBytes, File.ReadAllBytes(recipePath));
        Assert.Equal(overwriteBytes, File.ReadAllBytes(overwritePath));
        var afterApply = workspace.SnapshotWorkspace();

        var repeated = await PublishedProcessTestSupport.RunAsync(
            target,
            workspace.WorkspacePath,
            ["index", "--format=json"],
            workspace.EnvironmentVariables);

        Assert.Equal(0, repeated.ExitCode);
        Assert.Equal(string.Empty, repeated.StandardError);
        Assert.Equal(afterApply, workspace.SnapshotWorkspace());
        Assert.Equal(workflowSkillBytes, File.ReadAllBytes(workflowSkillPath));
        Assert.Equal(recipeBytes, File.ReadAllBytes(recipePath));
        Assert.Equal(overwriteBytes, File.ReadAllBytes(overwritePath));

        var diagnosed = await DiagnoseAsync(target, workspace);
        Assert.Equal(0, diagnosed.ExitCode);
        using var doctorDocument = JsonDocument.Parse(diagnosed.StandardOutput);
        Assert.Equal("completed", doctorDocument.RootElement.GetProperty("status").GetString());
        Assert.Empty(doctorDocument.RootElement.GetProperty("findings").EnumerateArray());
    }

    [Fact(DisplayName = "Doctor distinguishes current generated navigation, stale entries and authored Framework changes"),
        Trait("Feature", "doctor-generated-navigation"), Trait("Evidence", "EndToEnd")]
    public async Task NavigationAndAuthoredDriftKeepTheirOwnDiagnosis()
    {
        var target = PublishedExecutableTarget.Discover();
        using var workspace = PublishedExtensionInstallWorkspace.Create();
        await ApplyAsync(target, workspace, ["install", "--automatic", "--format=json"]);
        const string entrypoint = ".agents/memory/working/_working.md";
        var sourcePath = Path.Combine(workspace.WorkspacePath, ".agents/memory/working/project.md");
        await File.WriteAllTextAsync(sourcePath, "---\nopen-forge:\n  description: Project note\n  tags: [Note]\n---\n# Project\n\nAn authored project note.\n", TestContext.Current.CancellationToken);
        await ApplyAsync(target, workspace, ["index", entrypoint, "--format=json"]);
        var current = await DiagnoseAsync(target, workspace);
        Assert.Equal(0, current.ExitCode);

        var indexPath = Path.Combine(workspace.WorkspacePath, entrypoint);
        var lines = await File.ReadAllLinesAsync(indexPath, TestContext.Current.CancellationToken);
        Assert.Single(lines, line => line.Contains("(project.md)", StringComparison.Ordinal));
        await File.WriteAllLinesAsync(indexPath, lines.Where(line => !line.Contains("(project.md)", StringComparison.Ordinal)), TestContext.Current.CancellationToken);
        var stale = await DiagnoseAsync(target, workspace);
        Assert.Equal(2, stale.ExitCode);
        using (var document = JsonDocument.Parse(stale.StandardOutput))
        {
            Assert.Contains(Findings(document, "routes-metadata-overwrites-generated-navigation"), finding => Kind(finding) == "route.generated-region-stale");
        }

        await ApplyAsync(target, workspace, ["index", entrypoint, "--format=json"]);
        await File.AppendAllTextAsync(Path.Combine(workspace.WorkspacePath, ".agents/guidance/_guidance.md"), "\nAn intentional authored Framework edit.\n", TestContext.Current.CancellationToken);
        var changed = await DiagnoseAsync(target, workspace);
        Assert.Equal(2, changed.ExitCode);
        using var changedDocument = JsonDocument.Parse(changed.StandardOutput);
        Assert.Contains(Findings(changedDocument, "framework-lifecycle"), finding => Kind(finding) == "framework.managed-changed");
        Assert.Contains(Findings(changedDocument, "framework-lifecycle"), finding => Kind(finding) == "framework.partial-lifecycle");
    }

    [Fact(DisplayName = "Doctor reports duplicate generated Entries headings"),
        Trait("Feature", "doctor-generated-navigation"), Trait("Evidence", "EndToEnd")]
    public async Task DuplicateGeneratedHeadingsRemainDiagnosed()
    {
        var target = PublishedExecutableTarget.Discover();
        using var workspace = PublishedExtensionInstallWorkspace.Create();
        await ApplyAsync(target, workspace, ["install", "--automatic", "--format=json"]);
        var path = Path.Combine(workspace.WorkspacePath, ".agents/memory/working/_working.md");
        var source = await File.ReadAllTextAsync(path, TestContext.Current.CancellationToken);
        const string marker = "## Entries";
        Assert.Contains(marker, source, StringComparison.Ordinal);
        await File.WriteAllTextAsync(path, source.Replace(marker, "## Entries\n\n## Entries", StringComparison.Ordinal), TestContext.Current.CancellationToken);

        var run = await DiagnoseAsync(target, workspace);

        Assert.NotEqual(0, run.ExitCode);
        using var document = JsonDocument.Parse(run.StandardOutput);
        Assert.Contains(Findings(document, "routes-metadata-overwrites-generated-navigation"), finding => Kind(finding) == "route.generated-region-duplicate");
    }

    private static async Task<ProcessRunResult> ApplyAsync(
        PublishedExecutableTarget target,
        PublishedExtensionInstallWorkspace workspace,
        IReadOnlyList<string> arguments)
    {
        var run = await PublishedProcessTestSupport.RunAsync(target, workspace.WorkspacePath, arguments, workspace.EnvironmentVariables);
        Assert.Equal(string.Empty, run.StandardError);
        Assert.True(run.ExitCode == 0, $"Expected exit 0, got {run.ExitCode}. Stdout: {run.StandardOutput} Stderr: {run.StandardError}");
        return run;
    }

    private static async Task<ProcessRunResult> DiagnoseAsync(PublishedExecutableTarget target, PublishedExtensionInstallWorkspace workspace, string command = "doctor")
    {
        var arguments = command == "doctor"
            ? new[] { command, "--format=json", "--detail=full" }
            : new[] { command, "--format=json" };
        var run = await PublishedProcessTestSupport.RunWithoutWritesAsync(target, workspace.WorkspacePath, workspace.SnapshotWorkspace, arguments, workspace.EnvironmentVariables);
        Assert.Equal(string.Empty, run.StandardError);
        workspace.AssertPersistentLock();
        return run;
    }

    private static JsonElement[] Findings(JsonDocument document, string domain)
    {
        var category = domain switch
        {
            "workspace-entry" => "Workspace",
            "recovery-residuals" => "Recovery data",
            "routes-metadata-overwrites-generated-navigation" => "Routes and Entries",
            "local-references" => "Links",
            "framework-lifecycle" => "Framework files",
            "extension-lifecycle" => "Extensions",
            _ => throw new ArgumentOutOfRangeException(nameof(domain), domain, "The Doctor category is not defined."),
        };
        return document.RootElement.GetProperty("findings").EnumerateArray()
            .Where(item => item.GetProperty("category").GetString() == category)
            .ToArray();
    }

    private static string? Kind(JsonElement finding) => finding.GetProperty("code").GetString();

    private static void AssertTargetedIndexAction(JsonElement finding, string expectedCommand)
    {
        var action = Assert.Single(finding.GetProperty("actions").EnumerateArray());
        Assert.Equal("command", action.GetProperty("kind").GetString());
        Assert.Equal(expectedCommand, action.GetProperty("command").GetString());
        Assert.Equal(
            "Refresh the generated Entries in this catalogue.",
            action.GetProperty("reason").GetString());
    }
}
