using System.Text.Json;
using OpenForge.Cli.EndToEndTests.Shared.PublishedProcess;

namespace OpenForge.Cli.EndToEndTests;

public sealed class PublishedDoctorGeneratedNavigationProcessTests
{
    [Theory(DisplayName = "Doctor accepts current navigation generated by Extension installation"),
        InlineData("development", "doctor"), InlineData("development-toolkit", "doctor"),
        InlineData("development", "status"), InlineData("development-toolkit", "status"),
        Trait("Feature", "doctor-generated-navigation"), Trait("Evidence", "EndToEnd")]
    public async Task FreshExtensionNavigationIsNotFrameworkDrift(string id, string command)
    {
        var target = PublishedExecutableTarget.Discover();
        using var workspace = PublishedExtensionInstallWorkspace.Create();
        await ApplyAsync(target, workspace, ["install", "--automatic", "--json"]);
        await ApplyAsync(target, workspace, ["extension", "install", id, "--automatic", "--json"]);

        var run = await DiagnoseAsync(target, workspace, command);

        Assert.Equal(0, run.ExitCode);
        using var document = JsonDocument.Parse(run.StandardOutput);
        Assert.Equal("complete", document.RootElement.GetProperty("status").GetString());
        if (command == "doctor")
        {
            Assert.Empty(Findings(document, "framework-lifecycle"));
            Assert.Empty(Findings(document, "routes-metadata-overwrites-generated-navigation"));
        }
    }

    [Fact(DisplayName = "Doctor distinguishes current generated navigation, stale entries and authored Framework changes"),
        Trait("Feature", "doctor-generated-navigation"), Trait("Evidence", "EndToEnd")]
    public async Task NavigationAndAuthoredDriftKeepTheirOwnDiagnosis()
    {
        var target = PublishedExecutableTarget.Discover();
        using var workspace = PublishedExtensionInstallWorkspace.Create();
        await ApplyAsync(target, workspace, ["install", "--automatic", "--json"]);
        const string entrypoint = ".agents/memory/working/_working.md";
        var sourcePath = Path.Combine(workspace.WorkspacePath, ".agents/memory/working/project.md");
        await File.WriteAllTextAsync(sourcePath, "---\nopen-forge:\n  description: Project note\n  tags: [Note]\n---\n# Project\n\nAn authored project note.\n", TestContext.Current.CancellationToken);
        await ApplyAsync(target, workspace, ["index", entrypoint, "--json"]);
        var current = await DiagnoseAsync(target, workspace);
        Assert.Equal(0, current.ExitCode);

        var indexPath = Path.Combine(workspace.WorkspacePath, entrypoint);
        var lines = await File.ReadAllLinesAsync(indexPath, TestContext.Current.CancellationToken);
        Assert.Single(lines, line => line.Contains("(project.md)", StringComparison.Ordinal));
        await File.WriteAllLinesAsync(indexPath, lines.Where(line => !line.Contains("(project.md)", StringComparison.Ordinal)), TestContext.Current.CancellationToken);
        var stale = await DiagnoseAsync(target, workspace);
        Assert.Equal(2, stale.ExitCode);
        using (var document = JsonDocument.Parse(stale.StandardOutput))
        {
            Assert.Contains(Findings(document, "routes-metadata-overwrites-generated-navigation"), finding => Kind(finding) == "route.generated-region-stale");
        }

        await ApplyAsync(target, workspace, ["index", entrypoint, "--json"]);
        await File.AppendAllTextAsync(Path.Combine(workspace.WorkspacePath, ".agents/guidance/adaptive-collaboration.md"), "\nAn intentional authored Framework edit.\n", TestContext.Current.CancellationToken);
        var changed = await DiagnoseAsync(target, workspace);
        Assert.Equal(2, changed.ExitCode);
        using var changedDocument = JsonDocument.Parse(changed.StandardOutput);
        Assert.Contains(Findings(changedDocument, "framework-lifecycle"), finding => Kind(finding) == "framework.managed-changed");
        Assert.Contains(Findings(changedDocument, "framework-lifecycle"), finding => Kind(finding) == "framework.partial-lifecycle");
    }

    [Fact(DisplayName = "Doctor still reports malformed generated markers"),
        Trait("Feature", "doctor-generated-navigation"), Trait("Evidence", "EndToEnd")]
    public async Task MalformedGeneratedMarkersRemainDiagnosed()
    {
        var target = PublishedExecutableTarget.Discover();
        using var workspace = PublishedExtensionInstallWorkspace.Create();
        await ApplyAsync(target, workspace, ["install", "--automatic", "--json"]);
        var path = Path.Combine(workspace.WorkspacePath, ".agents/memory/working/_working.md");
        var source = await File.ReadAllTextAsync(path, TestContext.Current.CancellationToken);
        const string marker = "<!-- open-forge:generated-index:end -->";
        Assert.Contains(marker, source, StringComparison.Ordinal);
        await File.WriteAllTextAsync(path, source.Replace(marker, "<!-- missing end marker -->", StringComparison.Ordinal), TestContext.Current.CancellationToken);

        var run = await DiagnoseAsync(target, workspace);

        Assert.NotEqual(0, run.ExitCode);
        using var document = JsonDocument.Parse(run.StandardOutput);
        Assert.Contains(Findings(document, "routes-metadata-overwrites-generated-navigation"), finding => Kind(finding) == "route.generated-region-malformed");
    }

    private static async Task ApplyAsync(PublishedExecutableTarget target, PublishedExtensionInstallWorkspace workspace, IReadOnlyList<string> arguments)
    {
        var run = await PublishedProcessTestSupport.RunAsync(target, workspace.WorkspacePath, arguments, workspace.EnvironmentVariables);
        Assert.Equal(string.Empty, run.StandardError);
        Assert.Equal(0, run.ExitCode);
    }

    private static async Task<ProcessRunResult> DiagnoseAsync(PublishedExecutableTarget target, PublishedExtensionInstallWorkspace workspace, string command = "doctor")
    {
        var run = await PublishedProcessTestSupport.RunWithoutWritesAsync(target, workspace.WorkspacePath, workspace.SnapshotWorkspace, [command, "--json"], workspace.EnvironmentVariables);
        Assert.Equal(string.Empty, run.StandardError);
        workspace.AssertPersistentLock();
        return run;
    }

    private static JsonElement[] Findings(JsonDocument document, string domain)
        => Assert.Single(document.RootElement.GetProperty("result").GetProperty("domains").EnumerateArray(), item => item.GetProperty("domain").GetString() == domain)
            .GetProperty("findings").EnumerateArray().ToArray();

    private static string? Kind(JsonElement finding) => finding.GetProperty("kind").GetString();
}
