import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { appendFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { IsolatedNpm } from "./isolated-npm.ts";
import { stageWrapperPackage } from "../wrapper-stage.ts";
import { readPublication } from "../publication.ts";
import { publishArguments } from "../publish-packages.ts";
import { AllTargets } from "../../targets.ts";
import { recordWrapper } from "../wrapper-artifact.ts";

for (const targets of [AllTargets, ["osx-x64", "win-x64"]] as const)
  test(`wrapper publication validates a licensed ${targets.join(",")} tarball without native artifacts`, (context) => {
    const root = mkdtempSync(join(tmpdir(), "open-forge-wrapper-publication-"));
    context.after(() => rmSync(root, { recursive: true, force: true }));
    const version = "0.0.0";
    writeFileSync(join(root, "package.json"), JSON.stringify({ version }));
    writeFileSync(join(root, "LICENSE"), "MIT fixture license\n");
    writeFileSync(join(root, "README.md"), "# Fixture readme\n");
    const git = (args: string[]) => execFileSync("git", args, { cwd: root, stdio: "pipe" });
    git(["init", "--quiet"]);
    git(["add", "package.json", "LICENSE", "README.md"]);
    git(["-c", "user.name=Publication Fixture", "-c", "user.email=fixture@example.invalid", "-c", "commit.gpgsign=false", "commit", "--quiet", "-m", "Fixture"]);
    const directory = join(root, "artifacts/delivery/wrapper");
    const build = join(directory, "build");
    mkdirSync(join(build, "npm"), { recursive: true });
    writeFileSync(join(build, "npm/open-forge.js"), "#!/usr/bin/env node\n");
    writeFileSync(join(build, "package-model.js"), "export const platforms = {};\n");
    const stage = join(directory, "stage");
    stageWrapperPackage(root, stage, version, build, targets);
    const npm = new IsolatedNpm(join(root, "scratch"));
    const packed = npm.pack(stage, join(directory, "packages"));
    recordWrapper(root, packed.path, version, targets);
    assert.deepEqual(packed.files, ["LICENSE", "README.md", "bin/open-forge.js", "package-model.js", "package.json"]);
    const publication = readPublication(root, "wrapper");
    assert.equal(publication.name, "@thelithiumforge/open-forge");
    assert.equal(publication.tarball, packed.path);
    assert.equal(publication.dirty, false);
    assert.equal(Object.keys(publication.optionalDependencies ?? {}).length, targets.length);
    assert.equal(existsSync(join(root, "artifacts/publish")), false);
    assert.deepEqual(publishArguments(publication, "preview"), ["publish", packed.path, "--access", "public", "--tag", "preview", "--ignore-scripts"]);
    assert.throws(() => publishArguments(publication, "preview; echo unsafe"));
    assert.throws(() => publishArguments({ ...publication, version: "0.1.0-beta.1" }, "latest"), /Prereleases/u);
    const original = readFileSync(packed.path);
    appendFileSync(packed.path, "changed");
    assert.throws(() => readPublication(root, "wrapper"), /Package bytes changed/u);
    writeFileSync(packed.path, original);
    writeFileSync(join(root, "LICENSE"), "changed license");
    assert.throws(() => readPublication(root, "wrapper"), /Source changed/u);
  });
